image: alpine

deploy:
  stage: deploy
  script:
    - echo Compressing...
  when: manual
  artifacts:
    name: "battlesnake-downloader-$CI_COMMIT_REF_NAME"
    paths: ["*.json", "icons/*.png", "*.html", "*.css", "*.js"]
    exclude: [".git/*"]
    expire_in: 1 week
